# Generated by Django 5.2.12 on 2026-03-09 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('사람인', '사람인'), ('원티드', '원티드'), ('공식홈페이지', '공식홈페이지'), ('추천', '추천'), ('기타', '기타')], default='기타', max_length=20)),
                ('job_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('진행중', '진행중'), ('합격', '합격'), ('불합격', '불합격'), ('포기', '포기')], default='진행중', max_length=10)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('서류', '서류'), ('코테', '코테'), ('커피챗', '커피챗'), ('면접', '면접'), ('과제', '과제')], max_length=10)),
                ('method', models.CharField(choices=[('온라인', '온라인'), ('오프라인', '오프라인')], max_length=10)),
                ('date', models.DateField()),
                ('result', models.CharField(choices=[('대기중', '대기중'), ('합격', '합격'), ('불합격', '불합격')], default='대기중', max_length=10)),
                ('memo', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='companies.company')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
