# Generated by Django 5.2.12 on 2026-03-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companystage_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystage',
            name='stage',
            field=models.CharField(max_length=50),
        ),
    ]
