# Generated by Django 5.2.12 on 2026-03-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_migrate_stage_result_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
