# Generated by Django 5.2.12 on 2026-03-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resumeevent_target_role_and_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeevent',
            name='user',
        ),
    ]
