# Generated by Django 5.2.12 on 2026-03-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_user_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeevent',
            options={'ordering': ['doc_type', '-modified_date']},
        ),
        migrations.AddField(
            model_name='resumeevent',
            name='doc_type',
            field=models.CharField(choices=[('이력서', '이력서'), ('포트폴리오', '포트폴리오'), ('자기소개서', '자기소개서')], default='이력서', max_length=20),
        ),
        migrations.AlterField(
            model_name='resumeevent',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
